[workspace]
authors = ["Nicholas A. Del Grosso <delgrosso.nick@gmail.com>"]
channels = ["conda-forge"]
name = "hhai-repo"
platforms = ["win-64"]
version = "0.1.0"

[dependencies]
python = "3.12.*"
pip = ">=25.2,<26"
pytest = ">=8.4.2,<9"
ipytest = ">=0.14.2,<0.15"
hypothesis = ">=6.142.4,<7"
pydantic = ">=2.12.5,<3"

[pypi-dependencies]
ipykernel = ">=6.30.1, <7"
pre-commit = ">=4.3.0, <5"
numpy = ">=2.3.4, <3"
pandas = ">=2.3.3, <3"
beartype = ">=0.22.8, <0.23"
attrs = "*"
cattrs = ">=25.3.0, <26"
pandera = ">=0.27.0, <0.28"
pydantic-ai = ">=1.28.0, <2"
